/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge */

#ifndef _Included_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
#define _Included_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_PLACE_LEFT
#define edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_PLACE_LEFT 0L
#undef edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_PLACE_TOP
#define edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_PLACE_TOP 1L
#undef edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_PLACE_RIGHT
#define edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_PLACE_RIGHT 2L
#undef edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_PLACE_BOTTOM
#define edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_PLACE_BOTTOM 3L
#undef edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_PLACE_NO_NEIGH
#define edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_PLACE_NO_NEIGH -1L
#undef edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_DIST_CONSTANT
#define edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_DIST_CONSTANT 3L
#undef edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_DIST_EXPONENTIAL
#define edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_DIST_EXPONENTIAL 6L
#undef edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_DIST_UNIFORM
#define edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_DIST_UNIFORM 16L
#undef edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_DIST_NORMAL
#define edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_DIST_NORMAL 12L
#undef edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_FIND_BLOCK_BY_LABEL
#define edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_FIND_BLOCK_BY_LABEL 1L
/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    createN
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_createN
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    executeN
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_executeN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    executeReturnIntN
 * Signature: (Ljava/lang/String;[I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_executeReturnIntN
  (JNIEnv *, jobject, jstring, jintArray);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    insertConstBlockN
 * Signature: (DIIII[I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_insertConstBlockN
  (JNIEnv *, jobject, jdouble, jint, jint, jint, jint, jintArray);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    makeConnectionN
 * Signature: (IIII)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_makeConnectionN
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    newModelN
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_newModelN
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    placeBlockN
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIII[I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_placeBlockN
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint, jintArray);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    pokeDoubleN
 * Signature: (Ljava/lang/String;ID)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_pokeDoubleN
  (JNIEnv *, jobject, jstring, jint, jdouble);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    pokeIntN
 * Signature: (Ljava/lang/String;II)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_pokeIntN
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    pokeStringN
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_pokeStringN
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    runSimulationN
 * Signature: (DDD)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_runSimulationN
  (JNIEnv *, jobject, jdouble, jdouble, jdouble);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    saveModelN
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_saveModelN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    closeExtendN
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_closeExtendN
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    openLibraryN
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_openLibraryN
  (JNIEnv *, jobject, jstring);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    releaseExtendN
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_releaseExtendN
  (JNIEnv *, jobject);

/*
 * Class:     edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge
 * Method:    isExtendRegistered
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_edu_cmu_sei_pacc_perf_eval_extend_ExtendMetaBridge_isExtendRegistered
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
